import { useEffect, useMemo, useState } from "react";
import api from "../lib/api";
import SearchSelect from "./SearchSelect";
import { Card, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, FormSelect, Modal, RowActionsMenu, errorMessage, formatMoney } from "./ui";

const initialForm = { id_servicio: "", alcance: "casa", responsable_pago: "inquilino", pagador_factura: "propietario", monto_base: "", estado: "activo", observacion: "" };
const servicioLabel = (s:any) => `${s.nombre_servicio || "Servicio"} — ${s.descripcion || "sin descripción"} — ${s.estado || "sin estado"}`;
const servicioSearchText = (s:any) => [s.id_servicio, s.nombre_servicio, s.descripcion, s.estado].filter(Boolean).join(" ");

export default function ServiciosActivosManager({ idCasa, idCuarto, cuartoNombre }: { idCasa: string | number; idCuarto?: string | number; cuartoNombre?: string }) {
  const [items,setItems]=useState<any[]>([]); const [servicios,setServicios]=useState<any[]>([]); const [error,setError]=useState(""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<any>(null); const [form,setForm]=useState<any>({...initialForm, alcance: idCuarto ? "cuarto" : "casa"});
  const activos=servicios.filter((s)=>s.estado==="activo");
  const selectedServicio=useMemo(()=>servicios.find((s)=>String(s.id_servicio)===String(form.id_servicio))||null,[servicios,form.id_servicio]);
  const servicioNombre=(id:any)=>servicios.find((s)=>String(s.id_servicio)===String(id))?.nombre_servicio || "Servicio";
  const load=async()=>{ try{ setError(""); const params:any={id_casa:idCasa}; if(idCuarto) params.id_cuarto=idCuarto; const [{data:cfg},{data:svc}]=await Promise.all([api.get('/api/servicios-mensuales/activos/inmuebles',{params}),api.get('/api/servicios')]); setItems(cfg); setServicios(svc); } catch(e:any){ setError(errorMessage(e)); } };
  useEffect(()=>{ load(); },[idCasa,idCuarto]);
  const startCreate=()=>{ setEditing(null); setForm({...initialForm, alcance:idCuarto?"cuarto":"casa"}); setOpen(true); };
  const startEdit=(x:any)=>{ setEditing(x); setForm({id_servicio:String(x.id_servicio), alcance:x.alcance || (x.id_cuarto?"cuarto":"casa"), responsable_pago:x.responsable_pago||"inquilino", pagador_factura:x.pagador_factura||"propietario", monto_base:x.monto_base ?? "", estado:x.estado||"activo", observacion:x.observacion||""}); setOpen(true); };
  const save=async(e:React.FormEvent)=>{ e.preventDefault(); try{ const payload:any={...form,id_servicio:Number(form.id_servicio),id_casa:Number(idCasa),id_cuarto:idCuarto?Number(idCuarto):null,monto_base:form.monto_base===""?null:Number(form.monto_base)}; Object.keys(payload).forEach(k=>{ if(payload[k]==="") payload[k]=null; }); if(editing) await api.put(`/api/servicios-mensuales/activos/inmuebles/${editing.id_servicio_activo}`,payload); else await api.post('/api/servicios-mensuales/activos/inmuebles',payload); setOpen(false); setEditing(null); await load(); } catch(e:any){ setError(errorMessage(e)); } };
  const rows=items.map((x)=>({...x, servicio:servicioNombre(x.id_servicio), alcance_legible:x.alcance==="cuarto"?`Cuarto ${cuartoNombre || "seleccionado"}`:"Casa completa", responsable:x.responsable_pago==="inquilino"?"Inquilino":"Propietario", pagador:x.pagador_factura==="inquilino_directo"?"Inquilino directo":"Propietario", monto:formatMoney(x.monto_base)}));
  return <Card title={idCuarto?"Servicios activos del cuarto":"Servicios activos de la casa"} description="Configuración base para proponer servicios mensuales del periodo." action={<button className="btn btn-primary btn-sm" onClick={startCreate}>+ Agregar servicio activo</button>}><ErrorMessage message={error}/><DataTable rows={rows} columns={["servicio","alcance_legible","responsable","pagador","monto","estado","observacion"]} getKey={(r)=>r.id_servicio_activo} emptyState={<EmptyState title="No hay servicios activos configurados." description="Agrega servicios base para proponerlos luego en el periodo." action={<button className="btn btn-primary" onClick={startCreate}>+ Agregar servicio activo</button>} icon="💡"/>} actions={(r)=><RowActionsMenu items={[{label:"Editar", onClick:()=>startEdit(r)}, {label:r.estado==="activo"?"Inactivar":"Activar", onClick:async()=>{ await api.put(`/api/servicios-mensuales/activos/inmuebles/${r.id_servicio_activo}`,{estado:r.estado==="activo"?"inactivo":"activo"}); await load(); }}]} />}/><Modal open={open} title={editing?"Editar servicio activo":"Agregar servicio activo"} description="Define el servicio base, responsable y monto sugerido." onClose={()=>setOpen(false)} footer={<FormActions formId="servicio-activo-form" onCancel={()=>setOpen(false)} submitLabel="Guardar"/>}><form id="servicio-activo-form" onSubmit={save} className="form-grid"><SearchSelect label="Servicio base" required items={activos} selectedItem={selectedServicio} onSelect={(s)=>setForm({...form,id_servicio:s?String(s.id_servicio):""})} getKey={(s)=>s.id_servicio} getOptionLabel={servicioLabel} getSelectedLabel={servicioLabel} getSearchText={servicioSearchText} placeholder="Buscar servicio" emptyItemsMessage="No hay servicios activos." noResultsMessage="No se encontraron servicios."/><FormSelect label="Alcance" required value={form.alcance} options={[{label:idCuarto?`Cuarto ${cuartoNombre || "seleccionado"}`:"Casa completa",value:idCuarto?"cuarto":"casa"}]} onChange={(v)=>setForm({...form,alcance:v})}/><FormSelect label="Responsable" required value={form.responsable_pago} options={[{label:"Inquilino",value:"inquilino"},{label:"Propietario",value:"propietario"}]} onChange={(v)=>setForm({...form,responsable_pago:v})}/><FormSelect label="Pagador factura" required value={form.pagador_factura} options={[{label:"Propietario",value:"propietario"},{label:"Inquilino directo",value:"inquilino_directo"}]} onChange={(v)=>setForm({...form,pagador_factura:v})}/><FormInput label="Monto base" value={form.monto_base} onChange={(v)=>setForm({...form,monto_base:v})}/><FormSelect label="Estado" value={form.estado} options={[{label:"Activo",value:"activo"},{label:"Inactivo",value:"inactivo"}]} onChange={(v)=>setForm({...form,estado:v})}/><FormInput label="Observación" value={form.observacion} onChange={(v)=>setForm({...form,observacion:v})}/></form></Modal></Card>;
}
