import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, ErrorMessage, FormInput, PageHeader, errorMessage } from "../components/ui";
const toNum = (v: string) => (v === "" ? null : Number(v));
const initialForm = { id_inquilino: "", id_cuarto: "", fecha_inicio: "", fecha_fin: "", monto_alquiler: "", dia_pago: "1", garantia: "", estado: "activo", observacion: "" };
const fields = Object.keys(initialForm);
export default function AlquileresPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm);
  const load = async () => { try { setError(""); const { data } = await api.get('/api/alquileres'); setItems(data); } catch (e:any) { setError(errorMessage(e)); } }; useEffect(() => { load(); }, []);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const payload = { ...form, id_inquilino: toNum(form.id_inquilino), id_cuarto: toNum(form.id_cuarto), monto_alquiler: toNum(form.monto_alquiler), dia_pago: toNum(form.dia_pago), garantia: toNum(form.garantia), fecha_fin: form.fecha_fin || null, observacion: form.observacion || null }; await api.post('/api/alquileres', payload); setForm(initialForm); await load(); } catch (e:any) { setError(errorMessage(e)); } };
  const finalizar = async (id:number) => { try { await api.post(`/api/alquileres/${id}/finalizar`); await load(); } catch (e:any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader title="Alquileres" description="Vincula inquilinos con cuartos y controla el estado del contrato." action={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Nuevo alquiler" description="Crea un alquiler activo o registra su información contractual."><form onSubmit={create}><div className="form-grid">{fields.map(k=><FormInput key={k} label={k} value={form[k]} onChange={(v)=>setForm({...form,[k]:v})}/>)}</div><div className="form-actions"><button className="btn btn-primary" type="submit">Guardar alquiler</button><button className="btn btn-secondary" type="button" onClick={()=>setForm(initialForm)}>Cancelar</button></div></form></Card><Card title="Listado de alquileres" description="Contratos registrados y acciones disponibles."><DataTable rows={items} columns={["id_alquiler","id_inquilino","id_cuarto","fecha_inicio","fecha_fin","monto_alquiler","dia_pago","estado"]} getKey={(r)=>r.id_alquiler} actions={(x)=><button className="btn btn-danger btn-sm" onClick={()=>finalizar(x.id_alquiler)}>Finalizar</button>}/></Card></div>;
}
