import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import ContextHelp from "../components/ContextHelp";
import { Card, DataTable, ErrorMessage, Field, FormInput, PageHeader, errorMessage } from "../components/ui";

const toNum = (v: string) => (v === "" ? null : Number(v));
const initialForm = { id_inquilino: "", id_cuarto: "", fecha_inicio: "", fecha_fin: "", monto_alquiler: "", dia_pago: "1", garantia: "", estado: "activo", observacion: "" };
const contextFields = ["id_inquilino", "fecha_inicio", "fecha_fin", "monto_alquiler", "dia_pago", "garantia", "estado", "observacion"];

export default function AlquileresPage() {
  const { idCuarto } = useParams();
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>({...initialForm, id_cuarto: idCuarto || ""}); const [cuarto,setCuarto]=useState<any>(null); const [casa,setCasa]=useState<any>(null);
  const load = async () => { try { setError(""); const { data } = await api.get('/api/alquileres'); setItems(data); if(idCuarto){const cuartoResp=await api.get(`/api/cuartos/${idCuarto}`); setCuarto(cuartoResp.data); const casaResp=await api.get(`/api/casas/${cuartoResp.data.id_casa}`); setCasa(casaResp.data); setForm((f:any)=>({...f,id_cuarto:idCuarto,monto_alquiler:f.monto_alquiler || String(cuartoResp.data.precio_alquiler ?? "")}));} } catch (e:any) { setError(errorMessage(e)); } };
  useEffect(() => { load(); }, [idCuarto]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); if(!idCuarto){setError("Para crear un alquiler, primero selecciona un cuarto libre."); return;} try { const payload = { ...form, id_inquilino: toNum(form.id_inquilino), id_cuarto: Number(idCuarto), monto_alquiler: toNum(form.monto_alquiler), dia_pago: toNum(form.dia_pago), garantia: toNum(form.garantia), fecha_fin: form.fecha_fin || null, observacion: form.observacion || null }; await api.post('/api/alquileres', payload); setForm({...initialForm, id_cuarto:idCuarto}); await load(); } catch (e:any) { setError(errorMessage(e)); } };
  const finalizar = async (id:number) => { try { await api.post(`/api/alquileres/${id}/finalizar`); await load(); } catch (e:any) { setError(errorMessage(e)); } };
  if (!idCuarto) return <div className="page"><PageHeader title="Alquileres" description="Consulta contratos. Para crear uno nuevo debes partir desde un cuarto libre." action={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><ContextHelp message="Para crear un alquiler, primero selecciona un cuarto libre." to="/cuartos" label="Ir a cuartos"/><Card title="Listado de alquileres" description="Contratos registrados y acciones disponibles."><DataTable rows={items} columns={["id_alquiler","id_inquilino","id_cuarto","fecha_inicio","fecha_fin","monto_alquiler","dia_pago","estado"]} getKey={(r)=>r.id_alquiler} actions={(x)=><button className="btn btn-danger btn-sm" onClick={()=>finalizar(x.id_alquiler)}>Finalizar</button>}/></Card></div>;
  return <div className="page"><PageHeader title="Crear alquiler para este cuarto" description="El cuarto queda definido por el contexto; solo elige inquilino y datos del contrato." action={<Link className="btn btn-secondary" to={`/cuartos/${idCuarto}`}>Volver al cuarto</Link>} /><ErrorMessage message={error}/><Card title="Contexto seleccionado" description="No necesitas escribir el ID del cuarto."><div className="detail-grid"><div><strong>Casa</strong><span>{casa?.nombre_casa || '—'}</span></div><div><strong>Cuarto</strong><span>{cuarto?.numero_cuarto || idCuarto}</span></div><div><strong>Estado</strong><span>{cuarto?.estado || '—'}</span></div></div></Card>{String(cuarto?.estado).toLowerCase() !== 'libre' ? <ContextHelp message="Para crear un alquiler, primero selecciona un cuarto libre." to="/cuartos" label="Ir a cuartos"/> : <Card title="Nuevo alquiler" description="El payload mantiene id_cuarto con el valor del cuarto seleccionado."><form onSubmit={create}><div className="form-grid">{contextFields.map(k=><FormInput key={k} label={k} value={form[k]} onChange={(v)=>setForm({...form,[k]:v})}/>)}</div><div className="form-actions"><button className="btn btn-primary" type="submit">Guardar alquiler</button><Link className="btn btn-secondary" to={`/cuartos/${idCuarto}`}>Cancelar</Link></div></form></Card>}<Card title="Alquileres de este cuarto" description="Historial filtrado del cuarto seleccionado."><DataTable rows={items.filter((x)=>String(x.id_cuarto)===String(idCuarto))} columns={["id_alquiler","id_inquilino","fecha_inicio","fecha_fin","monto_alquiler","dia_pago","estado"]} getKey={(r)=>r.id_alquiler} actions={(x)=><button className="btn btn-danger btn-sm" onClick={()=>finalizar(x.id_alquiler)}>Finalizar</button>}/></Card></div>;
}
