import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import { BreadcrumbItem, Card, ContextSummary, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, Modal, PageHeader, RowActionsMenu, Tabs, errorMessage } from "../components/ui";

const initialForm = { nombre_casa: "", direccion: "", zona: "", ciudad: "", descripcion: "", estado: "activa", id_usuario_responsable: "" };
const cuartoForm = { id_casa: "", numero_cuarto: "", descripcion: "", precio_alquiler: "", estado: "libre", observacion: "" };
const casaFields = Object.keys(initialForm);
const cuartoFields = ["numero_cuarto", "descripcion", "precio_alquiler", "estado", "observacion"];

function CasaDetalle({ idCasa }: { idCasa: string }) {
  const [casa, setCasa] = useState<any>(null);
  const [cuartos, setCuartos] = useState<any[]>([]);
  const [egresos, setEgresos] = useState<any[]>([]);
  const [error, setError] = useState("");
  const [openCuarto, setOpenCuarto] = useState(false);
  const [form, setForm] = useState<any>({ ...cuartoForm, id_casa: idCasa });
  const breadcrumbs: BreadcrumbItem[] = [{ label: "Propiedades", to: "/casas" }, { label: casa?.nombre_casa || `Casa #${idCasa}` }];
  const load = async () => { try { setError(""); const [{ data: casaData }, { data: cuartosData }, egresosResp] = await Promise.all([api.get(`/api/casas/${idCasa}`), api.get(`/api/casas/${idCasa}/cuartos`), api.get("/api/egresos").catch(() => ({ data: [] }))]); setCasa(casaData); setCuartos(cuartosData); setEgresos((egresosResp.data || []).filter((x: any) => String(x.id_casa) === String(idCasa))); setForm((f: any) => ({ ...f, id_casa: idCasa })); } catch (e: any) { setError(errorMessage(e)); } };
  useEffect(() => { load(); }, [idCasa]);
  const createCuarto = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form, id_casa: Number(idCasa) }; payload.precio_alquiler = payload.precio_alquiler === "" ? null : Number(payload.precio_alquiler); Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/cuartos", payload); setForm({ ...cuartoForm, id_casa: idCasa }); setOpenCuarto(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={breadcrumbs} title={casa?.nombre_casa || `Casa #${idCasa}`} description="Detalle de propiedad y accesos contextuales para administrar sus cuartos y gastos." action={<button className="btn btn-primary" onClick={() => setOpenCuarto(true)}>+ Crear cuarto</button>} secondaryAction={<Link className="btn btn-secondary" to="/casas">Volver a casas</Link>} /><ErrorMessage message={error}/><Tabs items={[{ label: "Resumen", to: `/casas/${idCasa}`, active: true }, { label: "Cuartos", to: `/casas/${idCasa}/cuartos` }, { label: "Egresos" }, { label: "Reporte de casa" }]} /><Card title="Resumen de casa" description="Información registrada de la propiedad."><ContextSummary items={[{ label: "Dirección", value: casa?.direccion }, { label: "Zona", value: casa?.zona }, { label: "Ciudad", value: casa?.ciudad }, { label: "Estado", value: casa?.estado }]} /></Card><Card title="Cuartos de esta casa" description="Administra únicamente los cuartos relacionados a esta propiedad." action={<button className="btn btn-primary btn-sm" onClick={() => setOpenCuarto(true)}>+ Crear cuarto</button>}><DataTable rows={cuartos} columns={["id_cuarto", "numero_cuarto", "descripcion", "precio_alquiler", "estado", "observacion"]} getKey={(r) => r.id_cuarto} emptyState={<EmptyState title="Esta casa todavía no tiene cuartos." description="Registra el primer cuarto para empezar a administrar alquileres." action={<button className="btn btn-primary" onClick={() => setOpenCuarto(true)}>+ Crear cuarto</button>} icon="🚪" />} actions={(r) => <div className="action-row"><Link className="btn btn-secondary btn-sm" to={`/cuartos/${r.id_cuarto}`}>Ver cuarto</Link><RowActionsMenu items={[{ label: "Administrar cuartos", to: `/casas/${idCasa}/cuartos` }, { label: "Crear alquiler", to: `/cuartos/${r.id_cuarto}/alquileres/nuevo`, disabled: String(r.estado).toLowerCase() !== "libre" }]} /></div>} /></Card><Card title="Egresos de la casa" description="Gastos asociados a esta propiedad con los datos actuales."><DataTable rows={egresos} columns={["id_egreso", "id_periodo", "id_cuarto", "concepto", "categoria", "monto"]} getKey={(r) => r.id_egreso} emptyState={<EmptyState title="No hay egresos registrados para esta casa." description="Cuando registres egresos asociados a esta casa aparecerán aquí." icon="📉" />} /></Card><Modal open={openCuarto} title="Crear cuarto" description={`Estás creando un cuarto para ${casa?.nombre_casa || `Casa #${idCasa}`}.`} onClose={() => setOpenCuarto(false)} footer={<FormActions formId="casa-cuarto-form" onCancel={() => setOpenCuarto(false)} submitLabel="Guardar cuarto" />}><ContextSummary items={[{ label: "Casa", value: casa?.nombre_casa || `Casa #${idCasa}` }]} /><form id="casa-cuarto-form" onSubmit={createCuarto} className="form-grid" style={{ marginTop: 16 }}>{cuartoFields.map((k) => <FormInput key={k} label={k} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Modal></div>;
}

export default function CasasPage() {
  const { idCasa } = useParams();
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/casas"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } };
  useEffect(() => { if (!idCasa) load(); }, [idCasa]);
  if (idCasa) return <CasaDetalle idCasa={idCasa} />;
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form }; if (payload.id_usuario_responsable === "") payload.id_usuario_responsable = null; else payload.id_usuario_responsable = Number(payload.id_usuario_responsable); Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/casas", payload); setForm(initialForm); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={[{ label: "Propiedades" }, { label: "Casas" }]} title="Casas" description="Área de propiedades: administra casas y desde cada una crea sus cuartos." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear casa</button>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Listado de casas" description="Usa la acción principal para entrar al detalle y continuar el flujo contextual."><DataTable rows={items} columns={["id_casa", "nombre_casa", "direccion", "zona", "ciudad", "estado", "id_usuario_responsable", "fecha_creacion"]} getKey={(r) => r.id_casa} emptyState={<EmptyState title="No hay casas registradas." description="Crea la primera casa para empezar a registrar cuartos y alquileres." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear casa</button>} icon="🏠" />} actions={(r) => <div className="action-row"><Link className="btn btn-primary btn-sm" to={`/casas/${r.id_casa}`}>Ver detalle</Link><RowActionsMenu items={[{ label: "Administrar cuartos", to: `/casas/${r.id_casa}/cuartos` }, { label: "Editar" }, { label: "Eliminar", danger: true }]} /></div>} /></Card><Modal open={open} title="Crear casa" description="Registra una propiedad con su responsable." onClose={() => setOpen(false)} footer={<FormActions formId="casa-form" onCancel={() => setOpen(false)} submitLabel="Guardar casa" />}><form id="casa-form" onSubmit={create} className="form-grid">{casaFields.map((k) => <FormInput key={k} label={k} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Modal></div>;
}
