import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, ErrorMessage, FormInput, PageHeader, errorMessage } from "../components/ui";
const initialForm = {id_casa: '', numero_cuarto: '', descripcion: '', precio_alquiler: '', estado: 'libre', observacion: ''};
const fields = Object.keys(initialForm);
export default function CuartosPage() {
  const [items,setItems]=useState<any[]>([]); const [error,setError]=useState(""); const [form,setForm]=useState<any>(initialForm);
  const load=async()=>{try{setError(""); const {data}=await api.get('/api/cuartos'); setItems(data);}catch(e:any){setError(errorMessage(e));}}; useEffect(()=>{load();},[]);
  const create=async(e:React.FormEvent)=>{e.preventDefault(); try{ const payload:any={...form}; if (payload.id_casa === "") payload.id_casa=null; else payload.id_casa=Number(payload.id_casa); if (payload.precio_alquiler === "") payload.precio_alquiler=null; else payload.precio_alquiler=Number(payload.precio_alquiler); Object.keys(payload).forEach((k)=>{ if(payload[k]==="") payload[k]=null; }); await api.post('/api/cuartos',payload); setForm(initialForm); await load(); }catch(e:any){setError(errorMessage(e));}};
  return <div className="page"><PageHeader title="Cuartos" description="Controla habitaciones, precios y estados de disponibilidad." action={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Nuevo cuarto" description="Crea un cuarto dentro de una casa existente."><form onSubmit={create}><div className="form-grid">{fields.map(k=><FormInput key={k} label={k} value={form[k]} onChange={(v)=>setForm({...form,[k]:v})}/>)}</div><div className="form-actions"><button className="btn btn-primary" type="submit">Guardar cuarto</button><button className="btn btn-secondary" type="button" onClick={()=>setForm(initialForm)}>Cancelar</button></div></form></Card><Card title="Listado de cuartos" description="Habitaciones registradas en el sistema."><DataTable rows={items} columns={["id_cuarto","id_casa","numero_cuarto","descripcion","precio_alquiler","estado","observacion","fecha_creacion"]} getKey={(r)=>r.id_cuarto}/></Card></div>;
}
