import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import ContextHelp from "../components/ContextHelp";
import { Card, DataTable, ErrorMessage, FormInput, PageHeader, errorMessage, formatMoney } from "../components/ui";

const initialForm = {id_casa: '', numero_cuarto: '', descripcion: '', precio_alquiler: '', estado: 'libre', observacion: ''};
const editableFields = ["numero_cuarto", "descripcion", "precio_alquiler", "estado", "observacion"];

export default function CuartosPage() {
  const { idCasa, idCuarto } = useParams();
  const isNewFromCasa = Boolean(idCasa && location.pathname.endsWith('/nuevo'));
  const [items,setItems]=useState<any[]>([]); const [error,setError]=useState(""); const [form,setForm]=useState<any>({...initialForm, id_casa: idCasa || ''}); const [casa,setCasa]=useState<any>(null); const [cuarto,setCuarto]=useState<any>(null);
  const load=async()=>{try{setError(""); if(idCuarto){const {data}=await api.get(`/api/cuartos/${idCuarto}`); setCuarto(data); const casaResp=await api.get(`/api/casas/${data.id_casa}`); setCasa(casaResp.data); return;} if(idCasa){const [{data:casaData},{data:cuartosData}]=await Promise.all([api.get(`/api/casas/${idCasa}`), api.get(`/api/casas/${idCasa}/cuartos`)]); setCasa(casaData); setItems(cuartosData); setForm((f:any)=>({...f,id_casa:idCasa})); return;} const {data}=await api.get('/api/cuartos'); setItems(data);}catch(e:any){setError(errorMessage(e));}};
  useEffect(()=>{load();},[idCasa,idCuarto]);
  const create=async(e:React.FormEvent)=>{e.preventDefault(); if(!idCasa){setError("Para crear un cuarto, primero selecciona una casa."); return;} try{ const payload:any={...form, id_casa: Number(idCasa)}; payload.precio_alquiler = payload.precio_alquiler===""?null:Number(payload.precio_alquiler); Object.keys(payload).forEach((k)=>{ if(payload[k]==="") payload[k]=null; }); await api.post('/api/cuartos',payload); setForm({...initialForm,id_casa:idCasa}); await load(); }catch(e:any){setError(errorMessage(e));}};
  if (idCuarto) return <div className="page"><PageHeader title={`Cuarto ${cuarto?.numero_cuarto || idCuarto}`} description="Detalle del cuarto y acción contextual para alquiler." action={<Link className="btn btn-secondary" to={cuarto ? `/casas/${cuarto.id_casa}/cuartos` : "/cuartos"}>Volver</Link>} /><ErrorMessage message={error}/><Card title="Detalle de cuarto" description="La creación de alquiler parte desde un cuarto libre."><div className="detail-grid"><div><strong>Casa</strong><span>{casa?.nombre_casa || cuarto?.id_casa || '—'}</span></div><div><strong>Cuarto</strong><span>{cuarto?.numero_cuarto || '—'}</span></div><div><strong>Alquiler</strong><span>{formatMoney(cuarto?.precio_alquiler)}</span></div><div><strong>Estado</strong><span>{cuarto?.estado || '—'}</span></div></div><div className="form-actions">{String(cuarto?.estado).toLowerCase()==='libre' ? <Link className="btn btn-primary" to={`/cuartos/${idCuarto}/alquileres/nuevo`}>Crear alquiler para este cuarto</Link> : <span className="error-message">Para crear un alquiler, primero selecciona un cuarto libre.</span>}</div></Card></div>;
  if (!idCasa) return <div className="page"><PageHeader title="Cuartos" description="Consulta cuartos. Para crear uno nuevo debes entrar desde una casa." action={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><ContextHelp message="Para crear un cuarto, primero selecciona una casa." to="/casas" label="Ir a casas"/><Card title="Listado general de cuartos" description="Vista de consulta; las acciones principales se realizan desde Casas."><DataTable rows={items} columns={["id_cuarto","id_casa","numero_cuarto","descripcion","precio_alquiler","estado","observacion","fecha_creacion"]} getKey={(r)=>r.id_cuarto} actions={(r)=><Link className="btn btn-secondary btn-sm" to={`/cuartos/${r.id_cuarto}`}>Ver detalle</Link>}/></Card></div>;
  return <div className="page"><PageHeader title={`Cuartos de ${casa?.nombre_casa || `Casa ${idCasa}`}`} description="Crea y consulta cuartos sin escribir manualmente el ID de casa." action={<Link className="btn btn-secondary" to={`/casas/${idCasa}`}>Detalle de casa</Link>} /><ErrorMessage message={error}/>{isNewFromCasa && <Card title="Nuevo cuarto" description={`Casa seleccionada: ${casa?.nombre_casa || idCasa}. El ID de casa se enviará automáticamente.`}><form onSubmit={create}><div className="form-grid">{editableFields.map(k=><FormInput key={k} label={k} value={form[k]} onChange={(v)=>setForm({...form,[k]:v})}/>)}</div><div className="form-actions"><button className="btn btn-primary" type="submit">Guardar cuarto</button><Link className="btn btn-secondary" to={`/casas/${idCasa}/cuartos`}>Cancelar</Link></div></form></Card>}<Card title="Listado de cuartos" description="Habitaciones asociadas a esta casa." action={!isNewFromCasa && <Link className="btn btn-primary" to={`/casas/${idCasa}/cuartos/nuevo`}>Crear cuarto</Link>}><DataTable rows={items} columns={["id_cuarto","numero_cuarto","descripcion","precio_alquiler","estado","observacion","fecha_creacion"]} getKey={(r)=>r.id_cuarto} actions={(r)=><Link className="btn btn-secondary btn-sm" to={`/cuartos/${r.id_cuarto}`}>Ver cuarto</Link>}/></Card></div>;
}
