import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import api from "../lib/api";
import ContextHelp from "../components/ContextHelp";
import { BreadcrumbItem, Card, ContextSummary, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, Modal, PageHeader, RowActionsMenu, Tabs, errorMessage, formatMoney } from "../components/ui";

const initialForm = { id_casa: "", numero_cuarto: "", descripcion: "", precio_alquiler: "", estado: "libre", observacion: "" };
const editableFields = ["numero_cuarto", "descripcion", "precio_alquiler", "estado", "observacion"];
const requiredFields = new Set(["numero_cuarto", "precio_alquiler"]);

export default function CuartosPage() {
  const { idCasa, idCuarto } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const isNewFromCasa = Boolean(idCasa && location.pathname.endsWith("/nuevo"));
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>({ ...initialForm, id_casa: idCasa || "" }); const [casa, setCasa] = useState<any>(null); const [cuarto, setCuarto] = useState<any>(null); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); if (idCuarto) { const { data } = await api.get(`/api/cuartos/${idCuarto}`); setCuarto(data); const casaResp = await api.get(`/api/casas/${data.id_casa}`); setCasa(casaResp.data); return; } if (idCasa) { const [{ data: casaData }, { data: cuartosData }] = await Promise.all([api.get(`/api/casas/${idCasa}`), api.get(`/api/casas/${idCasa}/cuartos`)]); setCasa(casaData); setItems(cuartosData); setForm((f: any) => ({ ...f, id_casa: idCasa })); return; } const { data } = await api.get("/api/cuartos"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } };
  useEffect(() => { load(); }, [idCasa, idCuarto]);
  useEffect(() => { setOpen(isNewFromCasa); }, [isNewFromCasa]);
  const closeModal = () => { setOpen(false); if (isNewFromCasa && idCasa) navigate(`/casas/${idCasa}/cuartos`); };
  const create = async (e: React.FormEvent) => { e.preventDefault(); if (!idCasa) { setError("Para crear un cuarto, primero selecciona una casa."); return; } try { const payload: any = { ...form, id_casa: Number(idCasa) }; payload.precio_alquiler = payload.precio_alquiler === "" ? null : Number(payload.precio_alquiler); Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/cuartos", payload); setForm({ ...initialForm, id_casa: idCasa }); closeModal(); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  if (idCuarto) {
    const breadcrumbs: BreadcrumbItem[] = [{ label: "Propiedades", to: "/casas" }, { label: casa?.nombre_casa || `Casa #${cuarto?.id_casa || ""}`, to: cuarto ? `/casas/${cuarto.id_casa}` : undefined }, { label: `Cuarto ${cuarto?.numero_cuarto || `#${idCuarto}`}` }];
    const libre = String(cuarto?.estado).toLowerCase() === "libre";
    return <div className="page"><PageHeader breadcrumbs={breadcrumbs} title={`Cuarto ${cuarto?.numero_cuarto || `#${idCuarto}`}`} description="Detalle del cuarto y acción contextual para alquiler." action={libre ? <Link className="btn btn-primary" to={`/cuartos/${idCuarto}/alquileres/nuevo`}>+ Crear alquiler</Link> : undefined} secondaryAction={<Link className="btn btn-secondary" to={cuarto ? `/casas/${cuarto.id_casa}/cuartos` : "/cuartos"}>Volver</Link>} /><ErrorMessage message={error}/><Tabs items={[{ label: "Resumen", active: true }, { label: "Alquiler activo" }]} /><Card title="Resumen del cuarto" description="La creación de alquiler parte desde un cuarto libre."><ContextSummary items={[{ label: "Casa", value: casa?.nombre_casa || cuarto?.id_casa }, { label: "Cuarto", value: cuarto?.numero_cuarto }, { label: "Alquiler", value: formatMoney(cuarto?.precio_alquiler) }, { label: "Estado", value: cuarto?.estado }]} />{libre ? <div className="form-actions"><Link className="btn btn-primary" to={`/cuartos/${idCuarto}/alquileres/nuevo`}>+ Crear alquiler para este cuarto</Link></div> : <div className="error-message" style={{ marginTop: 18 }}>Este cuarto no está libre. Para crear un alquiler, primero selecciona un cuarto libre.</div>}</Card><Card title="Alquiler activo" description="Información contextual disponible sin crear endpoints nuevos."><EmptyState title={libre ? "Este cuarto está libre." : "Este cuarto figura como ocupado."} description={libre ? "Puedes crear un alquiler desde la acción principal." : "Consulta la vista general de alquileres para revisar contratos relacionados."} action={libre ? <Link className="btn btn-primary" to={`/cuartos/${idCuarto}/alquileres/nuevo`}>+ Crear alquiler</Link> : <Link className="btn btn-secondary" to="/alquileres">Ver alquileres</Link>} icon="📄" /></Card></div>;
  }
  if (!idCasa) return <div className="page"><PageHeader breadcrumbs={[{ label: "Propiedades" }, { label: "Cuartos" }]} title="Cuartos" description="Consulta cuartos. Para crear uno nuevo debes entrar desde una casa." action={<Link className="btn btn-primary" to="/casas">Ir a casas</Link>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><ContextHelp message="Para crear un cuarto, primero selecciona una casa." to="/casas" label="Ir a casas"/><Card title="Listado general de cuartos" description="Vista de consulta; las acciones principales se realizan desde Casas."><DataTable rows={items} columns={["id_cuarto", "id_casa", "numero_cuarto", "descripcion", "precio_alquiler", "estado", "observacion", "fecha_creacion"]} getKey={(r) => r.id_cuarto} emptyState={<EmptyState title="No hay cuartos registrados." description="Primero selecciona una casa para crear sus cuartos." action={<Link className="btn btn-primary" to="/casas">Ir a casas</Link>} icon="🚪" />} actions={(r) => <div className="action-row"><Link className="btn btn-secondary btn-sm" to={`/cuartos/${r.id_cuarto}`}>Ver detalle</Link>{String(r.estado).toLowerCase() === "libre" && <Link className="btn btn-primary btn-sm" to={`/cuartos/${r.id_cuarto}/alquileres/nuevo`}>Crear alquiler</Link>}<RowActionsMenu items={[{ label: "Ver casa", to: `/casas/${r.id_casa}` }]} /></div>} /></Card></div>;
  const breadcrumbs: BreadcrumbItem[] = [{ label: "Propiedades", to: "/casas" }, { label: casa?.nombre_casa || `Casa #${idCasa}`, to: `/casas/${idCasa}` }, { label: "Cuartos" }];
  return <div className="page"><PageHeader breadcrumbs={breadcrumbs} title={`Cuartos de ${casa?.nombre_casa || `Casa #${idCasa}`}`} description="Crea y consulta cuartos sin escribir manualmente el ID de casa." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear cuarto</button>} secondaryAction={<Link className="btn btn-secondary" to={`/casas/${idCasa}`}>Detalle de casa</Link>} /><ErrorMessage message={error}/><Tabs items={[{ label: "Resumen", to: `/casas/${idCasa}` }, { label: "Cuartos", to: `/casas/${idCasa}/cuartos`, active: true }, { label: "Egresos" }, { label: "Reporte de casa" }]} /><Card title="Listado de cuartos" description="Habitaciones asociadas a esta casa."><DataTable rows={items} columns={["id_cuarto", "numero_cuarto", "descripcion", "precio_alquiler", "estado", "observacion", "fecha_creacion"]} getKey={(r) => r.id_cuarto} emptyState={<EmptyState title="Todavía no hay cuartos en esta casa." description="Registra el primer cuarto para empezar a administrar alquileres." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear cuarto</button>} icon="🚪" />} actions={(r) => <div className="action-row"><Link className="btn btn-secondary btn-sm" to={`/cuartos/${r.id_cuarto}`}>Ver detalle</Link>{String(r.estado).toLowerCase() === "libre" && <Link className="btn btn-primary btn-sm" to={`/cuartos/${r.id_cuarto}/alquileres/nuevo`}>Crear alquiler</Link>}<RowActionsMenu items={[{ label: "Ver casa", to: `/casas/${idCasa}` }, { label: "Editar" }]} /></div>} /></Card><Modal open={open} title="Crear cuarto" description={`Estás creando un cuarto para ${casa?.nombre_casa || `Casa #${idCasa}`}.`} onClose={closeModal} footer={<FormActions formId="cuarto-form" onCancel={closeModal} submitLabel="Guardar cuarto" />}><ContextSummary items={[{ label: "Casa", value: casa?.nombre_casa || `Casa #${idCasa}` }]} /><form id="cuarto-form" onSubmit={create} className="form-grid" style={{ marginTop: 16 }}>{editableFields.map((k) => <FormInput key={k} label={k} required={requiredFields.has(k)} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Modal></div>;
}
