import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, Drawer, EmptyState, ErrorMessage, FormActions, FormInput, PageHeader, RowActionsMenu, errorMessage } from "../components/ui";
const initialForm = { id_casa: "", id_periodo: "", id_cuarto: "", id_servicio_mensual: "", concepto: "", categoria: "otro", monto: "", fecha_egreso: "", metodo_pago: "", numero_comprobante: "", comprobante: "", observacion: "", registrado_por: "" };
const fields = Object.keys(initialForm);
export default function EgresosPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/egresos"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } }; useEffect(() => { load(); }, []);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form }; ["id_casa", "id_periodo", "id_cuarto", "id_servicio_mensual", "monto", "registrado_por"].forEach((k) => payload[k] = payload[k] === "" ? null : Number(payload[k])); Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/egresos", payload); setForm(initialForm); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={[{ label: "Propiedades" }, { label: "Egresos" }]} title="Egresos" description="Registra salidas de dinero por servicios, mantenimiento u otros conceptos." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear egreso</button>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Listado de egresos" description="Gastos registrados en el sistema."><DataTable rows={items} columns={["id_egreso", "id_casa", "id_periodo", "id_cuarto", "concepto", "categoria", "monto", "registrado_por"]} getKey={(r) => r.id_egreso} emptyState={<EmptyState title="No hay egresos registrados." description="Registra salidas de dinero asociadas a casa, periodo o cuarto." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear egreso</button>} icon="📉" />} actions={() => <RowActionsMenu items={[{ label: "Editar" }, { label: "Eliminar", danger: true }]} />} /></Card><Drawer open={open} title="Crear egreso" description="Mantén todos los campos actuales y el mismo payload hacia backend." onClose={() => setOpen(false)} footer={<FormActions formId="egreso-form" onCancel={() => setOpen(false)} submitLabel="Guardar egreso" />}><form id="egreso-form" onSubmit={create} className="form-grid">{fields.map((k) => <FormInput key={k} label={k} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Drawer></div>;
}
