import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, Drawer, EmptyState, ErrorMessage, FormActions, FormInput, PageHeader, RowActionsMenu, errorMessage } from "../components/ui";
const initialForm = { nombre: "", ci: "", telefono: "", correo: "", direccion_referencia: "", contacto_emergencia: "", telefono_emergencia: "", estado: "activo", observacion: "" };
const fields = Object.keys(initialForm);
export default function InquilinosPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/inquilinos"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } }; useEffect(() => { load(); }, []);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form }; Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/inquilinos", payload); setForm(initialForm); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={[{ label: "Personas y alquileres" }, { label: "Inquilinos" }]} title="Inquilinos" description="Registra datos personales, contacto y referencias de emergencia." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear inquilino</button>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Listado de inquilinos" description="Personas registradas para alquileres."><DataTable rows={items} columns={["id_inquilino", "nombre", "ci", "telefono", "correo", "contacto_emergencia", "estado", "fecha_creacion"]} getKey={(r) => r.id_inquilino} emptyState={<EmptyState title="No hay inquilinos registrados." description="Registra inquilinos para poder asociarlos a alquileres." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear inquilino</button>} icon="🤝" />} actions={() => <RowActionsMenu items={[{ label: "Editar" }, { label: "Eliminar", danger: true }]} />} /></Card><Drawer open={open} title="Crear inquilino" description="Mantén actualizada la información del ocupante." onClose={() => setOpen(false)} footer={<FormActions formId="inquilino-form" onCancel={() => setOpen(false)} submitLabel="Guardar inquilino" />}><form id="inquilino-form" onSubmit={create} className="form-grid">{fields.map((k) => <FormInput key={k} label={k} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Drawer></div>;
}
