import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import ContextHelp from "../components/ContextHelp";
import { useAuth } from "../contexts/AuthContext";
import { Card, DataTable, ErrorMessage, FormInput, PageHeader, errorMessage, formatMoney } from "../components/ui";
const initialForm = {monto_pagado:"",fecha_pago:"",metodo_pago:"",numero_comprobante:"",imagen_comprobante:"",observacion:"",estado:"valido"};
const contextFields = Object.keys(initialForm);
export default function PagosPage(){
  const { idCobro } = useParams(); const { user } = useAuth();
  const [items,setItems]=useState<any[]>([]); const [error,setError]=useState(""); const [form,setForm]=useState<any>(initialForm); const [cobro,setCobro]=useState<any>(null); const [casa,setCasa]=useState<any>(null); const [cuarto,setCuarto]=useState<any>(null);
  const load=async()=>{try{setError("");const {data}=await api.get('/api/pagos');setItems(idCobro ? data.filter((x:any)=>String(x.id_cobro)===String(idCobro)) : data); if(idCobro){const c=await api.get(`/api/cobros/${idCobro}`); setCobro(c.data); const [casaResp, cuartoResp]=await Promise.all([api.get(`/api/casas/${c.data.id_casa}`), api.get(`/api/cuartos/${c.data.id_cuarto}`)]); setCasa(casaResp.data); setCuarto(cuartoResp.data);}}catch(e:any){setError(errorMessage(e));}}; useEffect(()=>{load();},[idCobro]);
  const create=async(e:React.FormEvent)=>{e.preventDefault(); if(!idCobro || !cobro){setError("Para registrar un pago, primero selecciona un cobro."); return;} try{const payload:any={...form, id_cobro:Number(idCobro), id_detalle_cobro:null, id_inquilino:Number(cobro.id_inquilino), registrado_por:user?.id_usuario ?? null}; payload.monto_pagado=payload.monto_pagado===""?null:Number(payload.monto_pagado); Object.keys(payload).forEach(k=>payload[k]===""&&(payload[k]=null)); await api.post('/api/pagos',payload); setForm(initialForm); await load();}catch(e:any){setError(errorMessage(e));}};
  const anular=async(id:number)=>{try{await api.post(`/api/pagos/${id}/anular`); await load();}catch(e:any){setError(errorMessage(e));}};
  if(!idCobro) return <div className="page"><PageHeader title="Pagos" description="Consulta general. Para registrar un pago debes entrar desde un cobro." action={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><ContextHelp message="Para registrar un pago, primero selecciona un cobro." to="/periodos" label="Ir a periodos"/><Card title="Listado de pagos" description="Pagos registrados y acción de anulación."><DataTable rows={items} columns={["id_pago","id_cobro","id_inquilino","monto_pagado","metodo_pago","numero_comprobante","registrado_por","estado"]} getKey={(r)=>r.id_pago} actions={(x)=><button className="btn btn-danger btn-sm" onClick={()=>anular(x.id_pago)}>Anular</button>}/></Card></div>;
  return <div className="page"><PageHeader title="Registrar pago" description="El cobro se toma automáticamente del contexto; completa solo los datos del pago." action={<Link className="btn btn-secondary" to={cobro ? `/periodos/${cobro.id_periodo}/cobros` : "/cobros"}>Volver a cobros</Link>} /><ErrorMessage message={error}/><Card title="Datos del cobro" description="Verifica el saldo antes de registrar el pago."><div className="detail-grid"><div><strong>Inquilino</strong><span>{cobro?.id_inquilino || '—'}</span></div><div><strong>Casa</strong><span>{casa?.nombre_casa || cobro?.id_casa || '—'}</span></div><div><strong>Cuarto</strong><span>{cuarto?.numero_cuarto || cobro?.id_cuarto || '—'}</span></div><div><strong>Total</strong><span>{formatMoney(cobro?.total_a_pagar)}</span></div><div><strong>Pagado</strong><span>{formatMoney(cobro?.total_pagado)}</span></div><div><strong>Saldo pendiente</strong><span>{formatMoney(cobro?.saldo_pendiente)}</span></div></div></Card><Card title="Nuevo pago" description="No se solicita id_cobro manualmente; se envía el cobro seleccionado."><form onSubmit={create}><div className="form-grid">{contextFields.map(k=><FormInput key={k} label={k} value={form[k]} onChange={(v)=>setForm({...form,[k]:v})}/>)}</div><div className="form-actions"><button className="btn btn-primary" type="submit">Guardar pago</button><button className="btn btn-secondary" type="button" onClick={()=>setForm(initialForm)}>Cancelar</button></div></form></Card><Card title="Pagos de este cobro"><DataTable rows={items} columns={["id_pago","id_cobro","id_inquilino","monto_pagado","metodo_pago","numero_comprobante","registrado_por","estado"]} getKey={(r)=>r.id_pago} actions={(x)=><button className="btn btn-danger btn-sm" onClick={()=>anular(x.id_pago)}>Anular</button>}/></Card></div>;
}
