import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, ErrorMessage, FormInput, PageHeader, errorMessage } from "../components/ui";
const initialForm = {id_cobro:"",id_detalle_cobro:"",id_inquilino:"",monto_pagado:"",metodo_pago:"",numero_comprobante:"",imagen_comprobante:"",registrado_por:"",observacion:"",estado:"valido"};
const fields = Object.keys(initialForm);
export default function PagosPage(){
  const [items,setItems]=useState<any[]>([]); const [error,setError]=useState(""); const [form,setForm]=useState<any>(initialForm);
  const load=async()=>{try{setError("");const {data}=await api.get('/api/pagos');setItems(data);}catch(e:any){setError(errorMessage(e));}}; useEffect(()=>{load();},[]);
  const create=async(e:React.FormEvent)=>{e.preventDefault(); try{const payload:any={...form}; ['id_cobro','id_detalle_cobro','id_inquilino','registrado_por','monto_pagado'].forEach((k)=> payload[k]=payload[k]===""?null:Number(payload[k])); Object.keys(payload).forEach(k=>payload[k]===""&&(payload[k]=null)); await api.post('/api/pagos',payload); setForm(initialForm); await load();}catch(e:any){setError(errorMessage(e));}};
  const anular=async(id:number)=>{try{await api.post(`/api/pagos/${id}/anular`); await load();}catch(e:any){setError(errorMessage(e));}};
  return <div className="page"><PageHeader title="Pagos" description="Registra pagos recibidos y anula pagos cuando corresponda." action={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Nuevo pago" description="Mantiene los campos actuales para registrar el abono."><form onSubmit={create}><div className="form-grid">{fields.map(k=><FormInput key={k} label={k} value={form[k]} onChange={(v)=>setForm({...form,[k]:v})}/>)}</div><div className="form-actions"><button className="btn btn-primary" type="submit">Guardar pago</button><button className="btn btn-secondary" type="button" onClick={()=>setForm(initialForm)}>Cancelar</button></div></form></Card><Card title="Listado de pagos" description="Pagos registrados y acción de anulación."><DataTable rows={items} columns={["id_pago","id_cobro","id_inquilino","monto_pagado","metodo_pago","numero_comprobante","registrado_por","estado"]} getKey={(r)=>r.id_pago} actions={(x)=><button className="btn btn-danger btn-sm" onClick={()=>anular(x.id_pago)}>Anular</button>}/></Card></div>;
}
