import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import ContextHelp from "../components/ContextHelp";
import { BreadcrumbItem, Card, ConfirmDialog, ContextSummary, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, Modal, PageHeader, RowActionsMenu, errorMessage, formatMoney } from "../components/ui";
import { useAuth } from "../contexts/AuthContext";
const initialForm = { monto_pagado: "", fecha_pago: "", metodo_pago: "", numero_comprobante: "", imagen_comprobante: "", observacion: "", estado: "valido" };
const contextFields = Object.keys(initialForm);
const requiredFields = new Set(["monto_pagado"]);
export default function PagosPage() {
  const { idCobro } = useParams(); const { user } = useAuth();
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [cobro, setCobro] = useState<any>(null); const [casa, setCasa] = useState<any>(null); const [cuarto, setCuarto] = useState<any>(null); const [open, setOpen] = useState(Boolean(idCobro)); const [confirmId, setConfirmId] = useState<number | null>(null);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/pagos"); setItems(idCobro ? data.filter((x: any) => String(x.id_cobro) === String(idCobro)) : data); if (idCobro) { const c = await api.get(`/api/cobros/${idCobro}`); setCobro(c.data); const [casaResp, cuartoResp] = await Promise.all([api.get(`/api/casas/${c.data.id_casa}`), api.get(`/api/cuartos/${c.data.id_cuarto}`)]); setCasa(casaResp.data); setCuarto(cuartoResp.data); } } catch (e: any) { setError(errorMessage(e)); } }; useEffect(() => { load(); setOpen(Boolean(idCobro)); }, [idCobro]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); if (!idCobro || !cobro) { setError("Para registrar un pago, primero selecciona un cobro."); return; } try { const payload: any = { ...form, id_cobro: Number(idCobro), id_detalle_cobro: null, id_inquilino: Number(cobro.id_inquilino), registrado_por: user?.id_usuario ?? null }; payload.monto_pagado = payload.monto_pagado === "" ? null : Number(payload.monto_pagado); Object.keys(payload).forEach((k) => payload[k] === "" && (payload[k] = null)); await api.post("/api/pagos", payload); setForm(initialForm); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  const anular = async () => { if (!confirmId) return; try { await api.post(`/api/pagos/${confirmId}/anular`); setConfirmId(null); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  if (!idCobro) return <div className="page"><PageHeader breadcrumbs={[{ label: "FINANZAS / COBRANZA" }, { label: "Pagos / confirmaciones" }]} title="Pagos / confirmaciones" description="Consulta interna. Para registrar un pago debes entrar desde pagos / confirmaciones de un periodo." action={<Link className="btn btn-primary" to="/periodos">Ir a periodos</Link>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><ContextHelp message="Para registrar un pago, primero selecciona un cobro." to="/periodos" label="Ir a periodos"/><Card title="Listado de pagos" description="Pagos registrados y acción de anulación."><DataTable rows={items} columns={["id_pago", "id_cobro", "id_inquilino", "monto_pagado", "metodo_pago", "numero_comprobante", "registrado_por", "estado"]} getKey={(r) => r.id_pago} emptyState={<EmptyState title="No hay pagos registrados." description="Para registrar un pago, primero selecciona un cobro." action={<Link className="btn btn-primary" to="/periodos">Ir a periodos</Link>} icon="✅" />} actions={(x) => <div className="action-row"><RowActionsMenu items={[{ label: "Anular", danger: true, onClick: () => setConfirmId(x.id_pago) }]} /></div>} /></Card><ConfirmDialog open={confirmId !== null} title="Anular pago" message="Esta acción anulará el pago seleccionado." danger confirmLabel="Anular" onCancel={() => setConfirmId(null)} onConfirm={anular} /></div>;
  const breadcrumbs: BreadcrumbItem[] = [{ label: "FINANZAS / COBRANZA", to: "/periodos" }, { label: "Pagos / confirmaciones", to: cobro ? `/periodos/${cobro.id_periodo}/cobros` : "/periodos" }, { label: `Cobro #${idCobro}` }, { label: "Registrar pago" }];
  return <div className="page"><PageHeader breadcrumbs={breadcrumbs} title="Registrar pago" description="El cobro se toma automáticamente del contexto; completa solo los datos del pago." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Registrar pago</button>} secondaryAction={<Link className="btn btn-secondary" to={cobro ? `/periodos/${cobro.id_periodo}/cobros` : "/periodos"}>Volver a pagos / confirmaciones</Link>} /><ErrorMessage message={error}/><Card title="Datos del cobro" description="Verifica el saldo antes de registrar el pago."><ContextSummary items={[{ label: "Inquilino", value: cobro?.id_inquilino }, { label: "Casa", value: casa?.nombre_casa || cobro?.id_casa }, { label: "Cuarto", value: cuarto?.numero_cuarto || cobro?.id_cuarto }, { label: "Total", value: formatMoney(cobro?.total_a_pagar) }, { label: "Pagado", value: formatMoney(cobro?.total_pagado) }, { label: "Saldo pendiente", value: formatMoney(cobro?.saldo_pendiente) }]} /></Card><Card title="Pagos de este cobro"><DataTable rows={items} columns={["id_pago", "id_cobro", "id_inquilino", "monto_pagado", "metodo_pago", "numero_comprobante", "registrado_por", "estado"]} getKey={(r) => r.id_pago} emptyState={<EmptyState title="No hay pagos registrados para este cobro." description="Registra el primer pago usando el cobro seleccionado." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Registrar pago</button>} icon="✅" />} actions={(x) => <div className="action-row"><RowActionsMenu items={[{ label: "Anular", danger: true, onClick: () => setConfirmId(x.id_pago) }]} /></div>} /></Card><Modal open={open} title="Registrar pago" description={`Cobro #${idCobro} autollenado.`} onClose={() => setOpen(false)} footer={<FormActions formId="pago-form" onCancel={() => setOpen(false)} submitLabel="Guardar pago" />}><ContextSummary items={[{ label: "Cobro", value: `#${idCobro}` }, { label: "Casa", value: casa?.nombre_casa || cobro?.id_casa }, { label: "Cuarto", value: cuarto?.numero_cuarto || cobro?.id_cuarto }, { label: "Saldo", value: formatMoney(cobro?.saldo_pendiente) }]} /><form id="pago-form" onSubmit={create} className="form-grid" style={{ marginTop: 16 }}>{contextFields.map((k) => <FormInput key={k} label={k} required={requiredFields.has(k)} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Modal><ConfirmDialog open={confirmId !== null} title="Anular pago" message="Esta acción anulará el pago seleccionado." danger confirmLabel="Anular" onCancel={() => setConfirmId(null)} onConfirm={anular} /></div>;
}
