import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "../lib/api";
import { Card, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, Modal, PageHeader, RowActionsMenu, errorMessage } from "../components/ui";
const initialForm = { anio: "", mes: "", nombre_periodo: "", fecha_inicio: "", fecha_fin: "", estado: "abierto" };
const fields = Object.keys(initialForm);
const requiredFields = new Set(["anio", "mes", "nombre_periodo", "fecha_inicio", "fecha_fin"]);
export default function PeriodosPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/periodos"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } }; useEffect(() => { load(); }, []);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form }; if (payload.anio === "") payload.anio = null; else payload.anio = Number(payload.anio); if (payload.mes === "") payload.mes = null; else payload.mes = Number(payload.mes); Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/periodos", payload); setForm(initialForm); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={[{ label: "FINANZAS / COBRANZA" }, { label: "Periodos" }]} title="Periodos" description="El periodo es el contexto principal para cobranza, servicios, pagos / confirmaciones y recordatorios." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear periodo</button>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Listado de periodos" description="Abre un periodo para operar sus vistas internas sin escribir IDs manualmente."><DataTable rows={items} columns={["id_periodo", "anio", "mes", "nombre_periodo", "fecha_inicio", "fecha_fin", "estado", "fecha_creacion"]} getKey={(r) => r.id_periodo} emptyState={<EmptyState title="No hay periodos registrados." description="Crea el primer periodo para iniciar FINANZAS / COBRANZA." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear periodo</button>} icon="🗓" />} actions={(r) => <div className="action-row"><Link className="btn btn-primary btn-sm" to={`/periodos/${r.id_periodo}/trabajo-mensual`}>Abrir periodo</Link><RowActionsMenu items={[{ label: "Servicios", to: `/periodos/${r.id_periodo}/servicios-mensuales` }, { label: "Pagos / confirmaciones", to: `/periodos/${r.id_periodo}/cobros` }, { label: "Recordatorios", to: `/periodos/${r.id_periodo}/recordatorios` }, { label: "Cerrar periodo" }]} /></div>} /></Card><Modal open={open} title="Crear periodo" description="Registra año, mes y rango de fechas del periodo." onClose={() => setOpen(false)} footer={<FormActions formId="periodo-form" onCancel={() => setOpen(false)} submitLabel="Guardar periodo" />}><form id="periodo-form" onSubmit={create} className="form-grid">{fields.map((k) => <FormInput key={k} label={k} required={requiredFields.has(k)} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Modal></div>;
}
