import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import ContextHelp from "../components/ContextHelp";
import { BreadcrumbItem, Card, EmptyState, ErrorMessage, Field, PageHeader, Tabs, formatMoney } from "../components/ui";
function ReportMetric({ label, value, money = true }: { label: string; value: any; money?: boolean }) { return <div className="report-metric"><span>{label}</span><strong>{money ? formatMoney(value) : (value ?? "—")}</strong></div>; }
function ReportCards({ data }: { data: any }) {
  if (!data) return <EmptyState title="Consulta un reporte para visualizar resultados." description="Selecciona un periodo o una casa para ver el resumen." icon="📊" />;
  const ganancia = data.total_pagado !== undefined && data.total_egresos !== undefined ? Number(data.total_pagado) - Number(data.total_egresos) : undefined;
  return <div className="report-grid"><ReportMetric label="Total a cobrar" value={data.total_a_cobrar} /><ReportMetric label="Total pagado" value={data.total_pagado} /><ReportMetric label="Saldo pendiente" value={data.total_pendiente} /><ReportMetric label="Egresos servicios" value={data.total_egresos_servicios ?? data.total_egresos} /><ReportMetric label="Servicios facturados" value={data.monto_servicios_facturado_inquilinos} /><ReportMetric label="Servicios pagados" value={data.monto_servicios_pagado_inquilinos} /><ReportMetric label="Servicios pendientes" value={data.monto_servicios_pendiente_inquilinos} /><ReportMetric label="Parte propietario" value={data.parte_servicios_propietario} /><ReportMetric label="Neto caja propietario" value={data.costo_neto_caja_propietario} />{data.cantidad_cobros !== undefined && <ReportMetric label="Cobros" value={data.cantidad_cobros} money={false} />}{data.cantidad_pagados !== undefined && <ReportMetric label="Pagados" value={data.cantidad_pagados} money={false} />}{data.cantidad_pendientes !== undefined && <ReportMetric label="Pendientes" value={data.cantidad_pendientes} money={false} />}{data.cantidad_parciales !== undefined && <ReportMetric label="Parciales" value={data.cantidad_parciales} money={false} />}{data.cantidad_atrasados !== undefined && <ReportMetric label="Atrasados" value={data.cantidad_atrasados} money={false} />}{data.cobros !== undefined && <ReportMetric label="Cobros" value={data.cobros} money={false} />}{data.egresos !== undefined && <ReportMetric label="Egresos registrados" value={data.egresos} money={false} />}</div>;
}
export default function ReportesPage() {
  const { idPeriodo } = useParams();
  const [idPeriodoManual, setIdPeriodoManual] = useState(idPeriodo || ""); const [idCasa, setIdCasa] = useState(""); const [resumen, setResumen] = useState<any>(null); const [casa, setCasa] = useState<any>(null); const [error, setError] = useState(""); const [periodo, setPeriodo] = useState<any>(null);
  const periodoActivo = idPeriodo || idPeriodoManual;
  const cargarResumen = async () => { if (!periodoActivo) { setError("Para ver reportes del mes, primero selecciona un periodo."); return; } try { setError(""); const { data } = await api.get(`/api/reportes/resumen-periodo/${periodoActivo}`); setResumen(data); } catch (e: any) { setError(e?.response?.data?.detail || "Error"); } };
  const cargarCasa = async () => { if (!periodoActivo) { setError("Para ver reportes del mes, primero selecciona un periodo."); return; } try { setError(""); const { data } = await api.get(`/api/reportes/casa/${idCasa}/periodo/${periodoActivo}`); setCasa(data); } catch (e: any) { setError(e?.response?.data?.detail || "Error"); } };
  useEffect(() => { if (idPeriodo) { api.get(`/api/periodos/${idPeriodo}`).then(({ data }) => setPeriodo(data)).catch(() => null); cargarResumen(); } }, [idPeriodo]);
  const breadcrumbs: BreadcrumbItem[] = idPeriodo ? [{ label: "Gestión mensual", to: "/periodos" }, { label: periodo?.nombre_periodo || `Periodo #${idPeriodo}`, to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Reportes" }] : [{ label: "Reportes" }];
  return <div className="page"><PageHeader breadcrumbs={breadcrumbs} title={idPeriodo ? `Reportes de ${periodo?.nombre_periodo || `Periodo #${idPeriodo}`}` : "Reportes"} description={idPeriodo ? "Consulta automática del periodo seleccionado." : "Vista general de reportes para consulta manual."} action={idPeriodo ? <button className="btn btn-primary" onClick={cargarResumen}>Resumen periodo</button> : <Link className="btn btn-primary" to="/periodos">Ir a periodos</Link>} secondaryAction={idPeriodo && <Link className="btn btn-secondary" to={`/periodos/${idPeriodo}/trabajo-mensual`}>Trabajo mensual</Link>} /><ErrorMessage message={error}/>{idPeriodo && <Tabs items={[{ label: "Resumen", to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Servicios", to: `/periodos/${idPeriodo}/servicios-mensuales` }, { label: "Cobros", to: `/periodos/${idPeriodo}/cobros` }, { label: "Pagos", to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Reportes", to: `/periodos/${idPeriodo}/reportes`, active: true }]} />}{!idPeriodo && <ContextHelp message="Para ver reportes del mes, primero selecciona un periodo." to="/periodos" label="Ir a periodos"/>}<Card title="Filtros de reporte" description={idPeriodo ? "El ID de periodo viene de la ruta; opcionalmente filtra por casa." : "Ingresa los IDs requeridos y consulta la información."}><div className="form-grid">{!idPeriodo && <Field label="ID periodo"><input placeholder="Ej. 1" value={idPeriodoManual} onChange={(e) => setIdPeriodoManual(e.target.value)} /></Field>}<Field label="ID casa"><input placeholder="Ej. 1" value={idCasa} onChange={(e) => setIdCasa(e.target.value)} /></Field></div><div className="form-actions"><button className="btn btn-primary" onClick={cargarResumen}>Resumen periodo</button><button className="btn btn-secondary" onClick={cargarCasa}>Reporte casa</button></div></Card><Card title="Resumen del periodo" description="Totales generales del periodo seleccionado."><ReportCards data={resumen}/></Card><Card title="Reporte por casa" description="Totales filtrados por casa y periodo."><ReportCards data={casa}/></Card></div>;
}
