import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import ContextHelp from "../components/ContextHelp";
import SearchSelect from "../components/SearchSelect";
import { BreadcrumbItem, Card, EmptyState, ErrorMessage, Field, PageHeader, Tabs, formatMoney } from "../components/ui";
const periodoLabel = (p:any) => `${p.nombre_periodo || `Periodo #${p.id_periodo}`} — ${p.mes || "?"}/${p.anio || "?"} — ${p.fecha_inicio || "sin inicio"} a ${p.fecha_fin || "sin fin"} — ${p.estado || "sin estado"} — ID #${p.id_periodo}`;
const periodoSearchText = (p:any) => [p.id_periodo, p.nombre_periodo, p.mes, p.anio, p.fecha_inicio, p.fecha_fin, p.estado].filter(Boolean).join(" ");
const casaLabel = (c:any) => `${c.nombre_casa || `Casa #${c.id_casa}`} — ${c.direccion || "sin dirección"} — ${c.zona || "sin zona"} — ${c.ciudad || "sin ciudad"} — ${c.estado || "sin estado"} — ID #${c.id_casa}`;
const casaSearchText = (c:any) => [c.id_casa, c.nombre_casa, c.direccion, c.zona, c.ciudad, c.estado].filter(Boolean).join(" ");
function ReportMetric({ label, value, money = true }: { label: string; value: any; money?: boolean }) { return <div className="report-metric"><span>{label}</span><strong>{money ? formatMoney(value) : (value ?? "—")}</strong></div>; }
function ReportCards({ data }: { data: any }) {
  if (!data) return <EmptyState title="Consulta un reporte para visualizar resultados." description="Selecciona un periodo o una casa para ver el resumen." icon="📊" />;
  const ganancia = data.total_pagado !== undefined && data.total_egresos !== undefined ? Number(data.total_pagado) - Number(data.total_egresos) : undefined;
  return <div className="report-grid"><ReportMetric label="Total a cobrar" value={data.total_a_cobrar} /><ReportMetric label="Total pagado" value={data.total_pagado} /><ReportMetric label="Saldo pendiente" value={data.total_pendiente} /><ReportMetric label="Egresos servicios" value={data.total_egresos_servicios ?? data.total_egresos} /><ReportMetric label="Servicios facturados" value={data.monto_servicios_facturado_inquilinos} /><ReportMetric label="Servicios pagados" value={data.monto_servicios_pagado_inquilinos} /><ReportMetric label="Servicios pendientes" value={data.monto_servicios_pendiente_inquilinos} /><ReportMetric label="Parte propietario" value={data.parte_servicios_propietario} /><ReportMetric label="Neto caja propietario" value={data.costo_neto_caja_propietario} />{data.cantidad_cobros !== undefined && <ReportMetric label="Cobros" value={data.cantidad_cobros} money={false} />}{data.cantidad_pagados !== undefined && <ReportMetric label="Pagados" value={data.cantidad_pagados} money={false} />}{data.cantidad_pendientes !== undefined && <ReportMetric label="Pendientes" value={data.cantidad_pendientes} money={false} />}{data.cantidad_parciales !== undefined && <ReportMetric label="Parciales" value={data.cantidad_parciales} money={false} />}{data.cantidad_atrasados !== undefined && <ReportMetric label="Atrasados" value={data.cantidad_atrasados} money={false} />}{data.cobros !== undefined && <ReportMetric label="Cobros" value={data.cobros} money={false} />}{data.egresos !== undefined && <ReportMetric label="Egresos registrados" value={data.egresos} money={false} />}</div>;
}
export default function ReportesPage() {
  const { idPeriodo } = useParams();
  const [idPeriodoManual, setIdPeriodoManual] = useState(idPeriodo || ""); const [idCasa, setIdCasa] = useState(""); const [resumen, setResumen] = useState<any>(null); const [casa, setCasa] = useState<any>(null); const [error, setError] = useState(""); const [periodo, setPeriodo] = useState<any>(null); const [periodos, setPeriodos] = useState<any[]>([]); const [casas, setCasas] = useState<any[]>([]);
  const periodoActivo = idPeriodo || idPeriodoManual;
  const selectedPeriodo = idPeriodo ? periodo : (periodos.find((p)=>String(p.id_periodo)===String(idPeriodoManual)) || null);
  const selectedCasa = casas.find((c)=>String(c.id_casa)===String(idCasa)) || null;
  const cargarResumen = async () => { if (!periodoActivo) { setError("Para ver reportes del mes, primero selecciona un periodo."); return; } try { setError(""); const { data } = await api.get(`/api/reportes/resumen-periodo/${periodoActivo}`); setResumen(data); } catch (e: any) { setError(e?.response?.data?.detail || "Error"); } };
  const cargarCasa = async () => { if (!periodoActivo) { setError("Para ver reportes del mes, primero selecciona un periodo."); return; } try { setError(""); const { data } = await api.get(`/api/reportes/casa/${idCasa}/periodo/${periodoActivo}`); setCasa(data); } catch (e: any) { setError(e?.response?.data?.detail || "Error"); } };
  useEffect(() => { Promise.all([api.get("/api/periodos"), api.get("/api/casas")]).then(([p,c])=>{ setPeriodos(p.data); setCasas(c.data); }).catch(() => null); }, []);
  useEffect(() => { if (idPeriodo) { api.get(`/api/periodos/${idPeriodo}`).then(({ data }) => setPeriodo(data)).catch(() => null); cargarResumen(); } }, [idPeriodo]);
  const breadcrumbs: BreadcrumbItem[] = idPeriodo ? [{ label: "Gestión mensual", to: "/periodos" }, { label: periodo?.nombre_periodo || `Periodo #${idPeriodo}`, to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Reportes" }] : [{ label: "Reportes" }];
  return <div className="page"><PageHeader breadcrumbs={breadcrumbs} title={idPeriodo ? `Reportes de ${periodo?.nombre_periodo || `Periodo #${idPeriodo}`}` : "Reportes"} description={idPeriodo ? "Consulta automática del periodo seleccionado." : "Vista general de reportes para consulta manual."} action={idPeriodo ? <button className="btn btn-primary" onClick={cargarResumen}>Resumen periodo</button> : <Link className="btn btn-primary" to="/periodos">Ir a periodos</Link>} secondaryAction={idPeriodo && <Link className="btn btn-secondary" to={`/periodos/${idPeriodo}/trabajo-mensual`}>Trabajo mensual</Link>} /><ErrorMessage message={error}/>{idPeriodo && <Tabs items={[{ label: "Resumen", to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Servicios", to: `/periodos/${idPeriodo}/servicios-mensuales` }, { label: "Cobros", to: `/periodos/${idPeriodo}/cobros` }, { label: "Pagos", to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Reportes", to: `/periodos/${idPeriodo}/reportes`, active: true }]} />}{!idPeriodo && <ContextHelp message="Para ver reportes del mes, primero selecciona un periodo." to="/periodos" label="Ir a periodos"/>}<Card title="Filtros de reporte" description={idPeriodo ? "El ID de periodo viene de la ruta; opcionalmente filtra por casa." : "Ingresa los IDs requeridos y consulta la información."}><div className="form-grid">{!idPeriodo ? <SearchSelect label="Periodo" required items={periodos} selectedItem={selectedPeriodo} onSelect={(p)=>setIdPeriodoManual(p?String(p.id_periodo):"")} getKey={(p)=>p.id_periodo} getOptionLabel={periodoLabel} getSelectedLabel={periodoLabel} getSearchText={periodoSearchText} placeholder="Buscar por nombre, mes, año, fechas, estado o ID..." emptyItemsMessage="No hay periodos registrados." noResultsMessage="No se encontraron periodos." /> : <Field label="Periodo"><input value={periodo ? periodoLabel(periodo) : `Periodo #${idPeriodo}`} disabled /></Field>}<SearchSelect label="Casa para reporte" items={casas} selectedItem={selectedCasa} onSelect={(c)=>setIdCasa(c?String(c.id_casa):"")} getKey={(c)=>c.id_casa} getOptionLabel={casaLabel} getSelectedLabel={casaLabel} getSearchText={casaSearchText} placeholder="Buscar por nombre, dirección, zona, ciudad, estado o ID..." emptyItemsMessage="No hay casas registradas." noResultsMessage="No se encontraron casas." /></div><div className="form-actions"><button className="btn btn-primary" onClick={cargarResumen}>Resumen periodo</button><button className="btn btn-secondary" onClick={cargarCasa}>Reporte casa</button></div></Card><Card title="Resumen del periodo" description="Totales generales del periodo seleccionado."><ReportCards data={resumen}/></Card><Card title="Reporte por casa" description="Totales filtrados por casa y periodo."><ReportCards data={casa}/></Card></div>;
}
