import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, ErrorMessage, FormInput, PageHeader, errorMessage } from "../components/ui";
const initialForm = {id_periodo: '', id_servicio: '', id_casa: '', id_cuarto: '', monto: '', responsable_pago: 'inquilino', estado_pago: 'pendiente', metodo_pago: '', fecha_pago: '', numero_comprobante: '', observacion: ''};
const fields = Object.keys(initialForm);
export default function ServiciosMensualesPage() {
  const [items,setItems]=useState<any[]>([]); const [error,setError]=useState(""); const [form,setForm]=useState<any>(initialForm);
  const load=async()=>{try{setError(""); const {data}=await api.get('/api/servicios-mensuales'); setItems(data);}catch(e:any){setError(errorMessage(e));}}; useEffect(()=>{load();},[]);
  const create=async(e:React.FormEvent)=>{e.preventDefault(); try{ const payload:any={...form}; ['id_periodo','id_servicio','id_casa','id_cuarto','monto'].forEach((k)=> payload[k]=payload[k]===""?null:Number(payload[k])); Object.keys(payload).forEach((k)=>{ if(payload[k]==="") payload[k]=null; }); await api.post('/api/servicios-mensuales',payload); setForm(initialForm); await load(); }catch(e:any){setError(errorMessage(e));}};
  return <div className="page"><PageHeader title="Servicios mensuales" description="Asigna servicios por periodo, casa y cuarto con responsable de pago." action={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Nuevo servicio mensual" description="Registra el monto y el responsable del servicio en el periodo."><form onSubmit={create}><div className="form-grid">{fields.map(k=><FormInput key={k} label={k} value={form[k]} onChange={(v)=>setForm({...form,[k]:v})}/>)}</div><div className="form-actions"><button className="btn btn-primary" type="submit">Guardar servicio mensual</button><button className="btn btn-secondary" type="button" onClick={()=>setForm(initialForm)}>Cancelar</button></div></form></Card><Card title="Listado de servicios mensuales" description="Servicios programados para cobros o egresos."><DataTable rows={items} columns={["id_servicio_mensual","id_periodo","id_servicio","id_casa","id_cuarto","monto","responsable_pago","estado_pago"]} getKey={(r)=>r.id_servicio_mensual}/></Card></div>;
}
