import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, ConfirmDialog, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, FormSelect, Modal, PageHeader, RowActionsMenu, errorMessage } from "../components/ui";
const initialForm = { nombre_servicio: "", descripcion: "", estado: "activo" };
export default function ServiciosPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [confirm, setConfirm] = useState<any>(null);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/servicios"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } };
  useEffect(() => { load(); }, []);
  const startCreate = () => { setEditing(null); setForm(initialForm); setOpen(true); };
  const startEdit = (item:any) => { setEditing(item); setForm({ nombre_servicio: item.nombre_servicio || "", descripcion: item.descripcion || "", estado: item.estado || "activo" }); setOpen(true); };
  const save = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form }; Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); if (editing) await api.put(`/api/servicios/${editing.id_servicio}`, payload); else await api.post("/api/servicios", payload); setForm(initialForm); setEditing(null); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  const setEstado = async (item:any, estado:string) => { try { await api.put(`/api/servicios/${item.id_servicio}`, { estado }); await load(); } catch (e:any) { setError(errorMessage(e)); } };
  const remove = async () => { if (!confirm) return; try { await api.delete(`/api/servicios/${confirm.id_servicio}`); setConfirm(null); await load(); } catch (e:any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={[{ label: "Configuración" }, { label: "Servicios" }]} title="Servicios" description="Catálogo de tipos de servicio. Activar o desactivar aquí solo controla si aparece para nuevos registros." action={<button className="btn btn-primary" onClick={startCreate}>+ Crear servicio</button>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Listado de servicios" description="El alcance, monto y responsable se deciden en cada periodo, no en el catálogo."><DataTable rows={items} columns={["nombre_servicio", "descripcion", "estado"]} getKey={(r) => r.id_servicio} emptyState={<EmptyState title="No hay servicios registrados." description="Agrega el primer concepto reutilizable para periodos mensuales." action={<button className="btn btn-primary" onClick={startCreate}>+ Crear servicio</button>} icon="🧾" />} actions={(x) => <RowActionsMenu items={[{ label: "Editar", onClick: () => startEdit(x) }, x.estado === "activo" ? { label: "Desactivar", onClick: () => setEstado(x, "inactivo") } : { label: "Activar", onClick: () => setEstado(x, "activo") }, { label: "Eliminar / desactivar", danger: true, onClick: () => setConfirm(x) }]} />} /></Card><Modal open={open} title={editing ? "Editar servicio" : "Crear servicio"} description="Define solo el catálogo: nombre, descripción y estado." onClose={() => setOpen(false)} footer={<FormActions formId="servicio-form" onCancel={() => setOpen(false)} submitLabel={editing ? "Guardar cambios" : "Guardar servicio"} />}><form id="servicio-form" onSubmit={save} className="form-grid"><FormInput label="Nombre servicio" required value={form.nombre_servicio} onChange={(v) => setForm({ ...form, nombre_servicio: v })} /><FormInput label="Descripción" value={form.descripcion} onChange={(v) => setForm({ ...form, descripcion: v })} /><FormSelect label="Estado" value={form.estado} options={[{ label: "Activo", value: "activo" }, { label: "Inactivo", value: "inactivo" }]} onChange={(v) => setForm({ ...form, estado: v })} /></form></Modal><ConfirmDialog open={!!confirm} title="Eliminar o desactivar servicio" message="Si el servicio tiene historial, el backend lo conservará y lo marcará como inactivo. Si no tiene historial, podrá eliminarse físicamente." danger confirmLabel="Continuar" onCancel={() => setConfirm(null)} onConfirm={remove} /></div>;
}
