import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, FormSelect, Modal, PageHeader, RowActionsMenu, errorMessage } from "../components/ui";
const initialForm = { nombre_servicio: "", descripcion: "", estado: "activo" };
export default function ServiciosPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [editing, setEditing] = useState<any>(null); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/servicios"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } }; useEffect(() => { load(); }, []);
  const startCreate = () => { setEditing(null); setForm(initialForm); setOpen(true); };
  const startEdit = (x: any) => { setEditing(x); setForm({ nombre_servicio: x.nombre_servicio || "", descripcion: x.descripcion || "", estado: x.estado || "activo" }); setOpen(true); };
  const save = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form }; Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); if (editing) await api.put(`/api/servicios/${editing.id_servicio}`, payload); else await api.post("/api/servicios", payload); setForm(initialForm); setEditing(null); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  const remove = async (x: any) => { try { await api.delete(`/api/servicios/${x.id_servicio}`); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={[{ label: "Configuración" }, { label: "Servicios" }]} title="Servicios" description="Mantén el catálogo de servicios usados en cobros y egresos." action={<button className="btn btn-primary" onClick={startCreate}>+ Crear servicio</button>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Listado de servicios" description="Los servicios inactivos conservan historial y no aparecen al crear servicios mensuales."><DataTable rows={items.map((x) => ({ ...x, estado_legible: x.estado === "activo" ? "Activo" : "Inactivo" }))} columns={["id_servicio", "nombre_servicio", "descripcion", "estado_legible"]} getKey={(r) => r.id_servicio} emptyState={<EmptyState title="No hay servicios registrados." description="Agrega el primer concepto reutilizable para periodos mensuales." action={<button className="btn btn-primary" onClick={startCreate}>+ Crear servicio</button>} icon="🧾" />} actions={(x) => <RowActionsMenu items={[{ label: "Editar", onClick: () => startEdit(x) }, { label: x.estado === "activo" ? "Desactivar" : "Activar", onClick: async () => { await api.put(`/api/servicios/${x.id_servicio}`, { estado: x.estado === "activo" ? "inactivo" : "activo" }); await load(); } }, { label: x.estado === "activo" ? "Eliminar / desactivar" : "Eliminar", danger: true, onClick: () => remove(x) }]} />} /></Card><Modal open={open} title={editing ? "Editar servicio" : "Crear servicio"} description="Agrega o modifica un concepto reutilizable para periodos mensuales." onClose={() => { setOpen(false); setEditing(null); }} footer={<FormActions formId="servicio-form" onCancel={() => { setOpen(false); setEditing(null); }} submitLabel={editing ? "Guardar cambios" : "Guardar servicio"} />}><form id="servicio-form" onSubmit={save} className="form-grid"><FormInput label="Nombre" required value={form.nombre_servicio} onChange={(v) => setForm({ ...form, nombre_servicio: v })} /><FormInput label="Descripción" value={form.descripcion} onChange={(v) => setForm({ ...form, descripcion: v })} /><FormSelect label="Estado" value={form.estado} options={[{ label: "Activo", value: "activo" }, { label: "Inactivo", value: "inactivo" }]} onChange={(v) => setForm({ ...form, estado: v })} /></form></Modal></div>;
}
