import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import api from "../lib/api";
import ContextHelp from "../components/ContextHelp";
import { BreadcrumbItem, Card, ContextSummary, DataTable, Drawer, EmptyState, ErrorMessage, FormActions, FormInput, PageHeader, RowActionsMenu, Tabs, errorMessage } from "../components/ui";
const initialForm = { id_periodo: "", id_servicio: "", id_casa: "", id_cuarto: "", monto: "", responsable_pago: "inquilino", estado_pago: "pendiente", metodo_pago: "", fecha_pago: "", numero_comprobante: "", observacion: "" };
const contextFields = ["id_servicio", "id_casa", "id_cuarto", "monto", "responsable_pago", "estado_pago", "metodo_pago", "fecha_pago", "numero_comprobante", "observacion"];
const requiredFields = new Set(["id_servicio", "id_casa", "monto", "responsable_pago"]);
export default function ServiciosMensualesPage() {
  const { idPeriodo } = useParams();
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>({ ...initialForm, id_periodo: idPeriodo || "" }); const [periodo, setPeriodo] = useState<any>(null); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/servicios-mensuales"); setItems(idPeriodo ? data.filter((x: any) => String(x.id_periodo) === String(idPeriodo)) : data); if (idPeriodo) { const p = await api.get(`/api/periodos/${idPeriodo}`); setPeriodo(p.data); setForm((f: any) => ({ ...f, id_periodo: idPeriodo })); } } catch (e: any) { setError(errorMessage(e)); } }; useEffect(() => { load(); }, [idPeriodo]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); if (!idPeriodo) { setError("Para registrar servicios mensuales, primero selecciona un periodo."); return; } try { const payload: any = { ...form, id_periodo: Number(idPeriodo) }; ["id_servicio", "id_casa", "id_cuarto", "monto"].forEach((k) => payload[k] = payload[k] === "" ? null : Number(payload[k])); Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/servicios-mensuales", payload); setForm({ ...initialForm, id_periodo: idPeriodo }); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  if (!idPeriodo) return <div className="page"><PageHeader breadcrumbs={[{ label: "Gestión mensual" }, { label: "Servicios mensuales" }]} title="Servicios mensuales" description="Consulta general. Para registrar servicios mensuales debes partir desde un periodo." action={<Link className="btn btn-primary" to="/periodos">Ir a periodos</Link>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><ContextHelp message="Para registrar servicios mensuales, primero selecciona un periodo." to="/periodos" label="Ir a periodos"/><Card title="Listado de servicios mensuales" description="Servicios programados para cobros o egresos."><DataTable rows={items} columns={["id_servicio_mensual", "id_periodo", "id_servicio", "id_casa", "id_cuarto", "monto", "responsable_pago", "estado_pago"]} getKey={(r) => r.id_servicio_mensual} emptyState={<EmptyState title="No hay servicios mensuales registrados." description="Primero selecciona un periodo para registrar servicios mensuales." action={<Link className="btn btn-primary" to="/periodos">Ir a periodos</Link>} icon="💡" />} /></Card></div>;
  const breadcrumbs: BreadcrumbItem[] = [{ label: "Gestión mensual", to: "/periodos" }, { label: periodo?.nombre_periodo || `Periodo #${idPeriodo}`, to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Servicios" }];
  return <div className="page"><PageHeader breadcrumbs={breadcrumbs} title="Servicios mensuales del periodo" description={`Periodo seleccionado: ${periodo?.nombre_periodo || `Periodo #${idPeriodo}`}. El ID de periodo se enviará automáticamente.`} action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Registrar servicio mensual</button>} secondaryAction={<Link className="btn btn-secondary" to={`/periodos/${idPeriodo}/trabajo-mensual`}>Trabajo mensual</Link>} /><ErrorMessage message={error}/><Tabs items={[{ label: "Resumen", to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Servicios", to: `/periodos/${idPeriodo}/servicios-mensuales`, active: true }, { label: "Cobros", to: `/periodos/${idPeriodo}/cobros` }, { label: "Pagos", to: `/periodos/${idPeriodo}/trabajo-mensual` }, { label: "Reportes", to: `/periodos/${idPeriodo}/reportes` }]} /><Card title="Servicios del periodo" description="Filtrado automáticamente por periodo."><DataTable rows={items} columns={["id_servicio_mensual", "id_servicio", "id_casa", "id_cuarto", "monto", "responsable_pago", "estado_pago"]} getKey={(r) => r.id_servicio_mensual} emptyState={<EmptyState title="Este periodo todavía no tiene servicios mensuales." description="Registra servicios para incluirlos en la gestión mensual." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Registrar servicio mensual</button>} icon="💡" />} actions={() => <RowActionsMenu items={[{ label: "Editar" }, { label: "Eliminar", danger: true }]} />} /></Card><Drawer open={open} title="Registrar servicio mensual" description="El periodo se toma automáticamente del contexto." onClose={() => setOpen(false)} footer={<FormActions formId="servicio-mensual-form" onCancel={() => setOpen(false)} submitLabel="Guardar servicio mensual" />}><ContextSummary items={[{ label: "Periodo", value: periodo?.nombre_periodo || `Periodo #${idPeriodo}` }, { label: "ID periodo", value: idPeriodo }]} /><form id="servicio-mensual-form" onSubmit={create} className="form-grid" style={{ marginTop: 16 }}>{contextFields.map((k) => <FormInput key={k} label={k} required={requiredFields.has(k)} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Drawer></div>;
}
