import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, FormSelect, Modal, PageHeader, RowActionsMenu, errorMessage } from "../components/ui";
const initialForm = { nombre_servicio: "", descripcion: "", estado: "activo" };
const fields = Object.keys(initialForm);
const requiredFields = new Set(["nombre_servicio"]);
export default function ServiciosPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/servicios"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } }; useEffect(() => { load(); }, []);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form }; Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/servicios", payload); setForm(initialForm); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={[{ label: "Configuración" }, { label: "Servicios" }]} title="Servicios" description="Mantén el catálogo de servicios usados en cobros y egresos." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear servicio</button>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Listado de servicios" description="Catálogo disponible."><DataTable rows={items} columns={["id_servicio", "nombre_servicio", "descripcion", "estado"]} getKey={(r) => r.id_servicio} emptyState={<EmptyState title="No hay servicios registrados." description="Agrega el primer concepto reutilizable para periodos mensuales." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear servicio</button>} icon="🧾" />} actions={() => <RowActionsMenu items={[{ label: "Editar" }, { label: "Eliminar", danger: true }]} />} /></Card><Modal open={open} title="Crear servicio" description="Agrega un concepto reutilizable para periodos mensuales." onClose={() => setOpen(false)} footer={<FormActions formId="servicio-form" onCancel={() => setOpen(false)} submitLabel="Guardar servicio" />}><form id="servicio-form" onSubmit={create} className="form-grid">{fields.map((k) => k === "estado" ? <FormSelect key={k} label={k} required={requiredFields.has(k)} value={form[k]} options={[{ label: "Activo", value: "activo" }, { label: "Inactivo", value: "inactivo" }]} onChange={(v) => setForm({ ...form, [k]: v })} /> : <FormInput key={k} label={k} required={requiredFields.has(k)} value={form[k]} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Modal></div>;
}
