import { useEffect, useState } from "react";
import api from "../lib/api";
import { Card, DataTable, EmptyState, ErrorMessage, FormActions, FormInput, FormSelect, Modal, PageHeader, RowActionsMenu, errorMessage } from "../components/ui";
const initialForm = { nombre: "", correo: "", telefono: "", password: "", rol: "admin", estado: "activo" };
const fields = Object.keys(initialForm);
const requiredFields = new Set(["nombre", "correo", "password"]);
export default function UsuariosPage() {
  const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [form, setForm] = useState<any>(initialForm); const [open, setOpen] = useState(false);
  const load = async () => { try { setError(""); const { data } = await api.get("/api/usuarios"); setItems(data); } catch (e: any) { setError(errorMessage(e)); } }; useEffect(() => { load(); }, []);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const payload: any = { ...form }; Object.keys(payload).forEach((k) => { if (payload[k] === "") payload[k] = null; }); await api.post("/api/usuarios", payload); setForm(initialForm); setOpen(false); await load(); } catch (e: any) { setError(errorMessage(e)); } };
  return <div className="page"><PageHeader breadcrumbs={[{ label: "Configuración" }, { label: "Usuarios" }]} title="Usuarios" description="Gestiona las personas con acceso al sistema y su información básica." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear usuario</button>} secondaryAction={<button className="btn btn-secondary" onClick={load}>Recargar</button>} /><ErrorMessage message={error}/><Card title="Listado de usuarios" description="Usuarios registrados actualmente."><DataTable rows={items} columns={["id_usuario", "nombre", "correo", "telefono", "rol", "estado", "fecha_creacion", "fecha_actualizacion"]} getKey={(r) => r.id_usuario} emptyState={<EmptyState title="No hay usuarios registrados." description="Crea el primer usuario para gestionar accesos." action={<button className="btn btn-primary" onClick={() => setOpen(true)}>+ Crear usuario</button>} icon="👤" />} actions={() => <RowActionsMenu items={[{ label: "Editar" }, { label: "Eliminar", danger: true }]} />} /></Card><Modal open={open} title="Crear usuario" description="Completa los mismos campos actuales para crear un acceso." onClose={() => setOpen(false)} footer={<FormActions formId="usuario-form" onCancel={() => setOpen(false)} submitLabel="Guardar usuario" />}><form id="usuario-form" onSubmit={create} className="form-grid">{fields.map((k) => k === "estado" ? <FormSelect key={k} label={k} required={requiredFields.has(k)} value={form[k]} options={[{ label: "Activo", value: "activo" }, { label: "Inactivo", value: "inactivo" }]} onChange={(v) => setForm({ ...form, [k]: v })} /> : <FormInput key={k} label={k} required={requiredFields.has(k)} value={form[k]} type={k === "password" ? "password" : "text"} onChange={(v) => setForm({ ...form, [k]: v })} />)}</form></Modal></div>;
}
