from datetime import datetime
from decimal import Decimal
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field
class ServicioMensualCreate(BaseModel): id_periodo:int; id_servicio:int; id_casa:int; id_cuarto:int|None=None; monto:Decimal=Field(ge=0); responsable_pago:Literal["inquilino","propietario"]; pagador_factura:Literal["propietario","inquilino_directo"]|None=None; estado_pago:Literal["pendiente","pagado","vencido"]="pendiente"; metodo_pago:str|None=None; fecha_pago:datetime|None=None; numero_comprobante:str|None=None; observacion:str|None=None; estado:Literal["activo","anulado"]="activo"
class ServicioMensualUpdate(BaseModel): id_periodo:int|None=None; id_servicio:int|None=None; id_casa:int|None=None; id_cuarto:int|None=None; monto:Decimal|None=Field(default=None,ge=0); responsable_pago:Literal["inquilino","propietario"]|None=None; pagador_factura:Literal["propietario","inquilino_directo"]|None=None; estado_pago:Literal["pendiente","pagado","vencido"]|None=None; metodo_pago:str|None=None; fecha_pago:datetime|None=None; numero_comprobante:str|None=None; observacion:str|None=None
class ServicioMensualResponse(BaseModel): model_config=ConfigDict(from_attributes=True); id_servicio_mensual:int; id_periodo:int; id_servicio:int; id_casa:int; id_cuarto:int|None=None; monto:Decimal; responsable_pago:str; pagador_factura:str="propietario"; estado_pago:str; metodo_pago:str|None=None; fecha_pago:datetime|None=None; numero_comprobante:str|None=None; observacion:str|None=None; estado:str="activo"; fecha_anulacion:datetime|None=None; motivo_anulacion:str|None=None; fecha_creacion:datetime
class DistribucionManualItem(BaseModel): id_alquiler:int|None=None; monto_asignado:Decimal=Field(ge=0)
class DistribucionManualUpdate(BaseModel): distribuciones:list[DistribucionManualItem]
