from datetime import datetime
from decimal import Decimal
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field
class ServicioMensualCreate(BaseModel): id_periodo:int; id_servicio:int; id_casa:int; id_cuarto:int|None=None; monto:Decimal=Field(ge=0); responsable_pago:Literal["inquilino","propietario"]; pagador_factura:Literal["propietario","inquilino_directo"]|None=None; estado_pago:Literal["pendiente","pagado","vencido"]="pendiente"; metodo_pago:str|None=None; fecha_pago:datetime|None=None; numero_comprobante:str|None=None; observacion:str|None=None; estado_recordatorio:str="no_preparado"; observacion_recordatorio:str|None=None; estado:Literal["activo","anulado"]="activo"
class ServicioMensualUpdate(BaseModel): id_periodo:int|None=None; id_servicio:int|None=None; id_casa:int|None=None; id_cuarto:int|None=None; monto:Decimal|None=Field(default=None,ge=0); responsable_pago:Literal["inquilino","propietario"]|None=None; pagador_factura:Literal["propietario","inquilino_directo"]|None=None; estado_pago:Literal["pendiente","pagado","vencido"]|None=None; metodo_pago:str|None=None; fecha_pago:datetime|None=None; numero_comprobante:str|None=None; observacion:str|None=None; estado_recordatorio:str|None=None; observacion_recordatorio:str|None=None
class ServicioMensualResponse(BaseModel): model_config=ConfigDict(from_attributes=True); id_servicio_mensual:int; id_periodo:int; id_servicio:int; id_casa:int; id_cuarto:int|None=None; monto:Decimal; responsable_pago:str; pagador_factura:str="propietario"; estado_pago:str; metodo_pago:str|None=None; fecha_pago:datetime|None=None; numero_comprobante:str|None=None; observacion:str|None=None; estado_recordatorio:str="no_preparado"; fecha_ultimo_contacto:datetime|None=None; observacion_recordatorio:str|None=None; estado:str="activo"; fecha_anulacion:datetime|None=None; motivo_anulacion:str|None=None; fecha_creacion:datetime
class DistribucionManualItem(BaseModel): id_alquiler:int|None=None; monto_asignado:Decimal=Field(ge=0)
class DistribucionManualUpdate(BaseModel): distribuciones:list[DistribucionManualItem]

class ServicioActivoCreate(BaseModel): id_servicio:int; id_casa:int; id_cuarto:int|None=None; alcance:Literal["casa","cuarto"]="casa"; responsable_pago:Literal["inquilino","propietario"]="inquilino"; pagador_factura:Literal["propietario","inquilino_directo"]="propietario"; monto_base:Decimal|None=Field(default=None,ge=0); estado:Literal["activo","inactivo"]="activo"; observacion:str|None=None
class ServicioActivoUpdate(BaseModel): id_servicio:int|None=None; id_casa:int|None=None; id_cuarto:int|None=None; alcance:Literal["casa","cuarto"]|None=None; responsable_pago:Literal["inquilino","propietario"]|None=None; pagador_factura:Literal["propietario","inquilino_directo"]|None=None; monto_base:Decimal|None=Field(default=None,ge=0); estado:Literal["activo","inactivo"]|None=None; observacion:str|None=None
class ServicioActivoResponse(ServicioActivoCreate): model_config=ConfigDict(from_attributes=True); id_servicio_activo:int; fecha_creacion:datetime

class RecordatorioUpdate(BaseModel): estado:Literal["no_preparado","preparado","enviado_manual","pendiente_envio","respondio","dijo_pago","pendiente_confirmar_pago","confirmado","sin_respuesta","error_envio"]; observacion:str|None=None
